/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.bomboplats.api;

import com.example.bomboplats.api.invoker.ApiCallback;
import com.example.bomboplats.api.invoker.ApiClient;
import com.example.bomboplats.api.invoker.ApiException;
import com.example.bomboplats.api.invoker.ApiResponse;
import com.example.bomboplats.api.invoker.Configuration;
import com.example.bomboplats.api.invoker.Pair;
import com.example.bomboplats.api.invoker.ProgressRequestBody;
import com.example.bomboplats.api.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.example.bomboplats.model.Direccion;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DireccionControllerApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DireccionControllerApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DireccionControllerApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deleteById
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Borrado exitoso. false: El registro no existe o se produjo un error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteByIdCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/direccion/delete/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteByIdValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteById(Async)");
        }

        return deleteByIdCall(id, _callback);

    }

    /**
     * Borrar una dirección por su Id
     * 
     * @param id  (required)
     * @return Boolean
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Borrado exitoso. false: El registro no existe o se produjo un error </td><td>  -  </td></tr>
     </table>
     */
    public Boolean deleteById(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<Boolean> localVarResp = deleteByIdWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Borrar una dirección por su Id
     * 
     * @param id  (required)
     * @return ApiResponse&lt;Boolean&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Borrado exitoso. false: El registro no existe o se produjo un error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Boolean> deleteByIdWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = deleteByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Borrar una dirección por su Id (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Borrado exitoso. false: El registro no existe o se produjo un error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteByIdAsync(@javax.annotation.Nonnull String id, final ApiCallback<Boolean> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for findAll4
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Direcciones encontradas </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontraron direcciones </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call findAll4Call(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/direccion/getAll";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call findAll4ValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return findAll4Call(_callback);

    }

    /**
     * Obtener direcciones
     * 
     * @return List&lt;Direccion&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Direcciones encontradas </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontraron direcciones </td><td>  -  </td></tr>
     </table>
     */
    public List<Direccion> findAll4() throws ApiException {
        ApiResponse<List<Direccion>> localVarResp = findAll4WithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Obtener direcciones
     * 
     * @return ApiResponse&lt;List&lt;Direccion&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Direcciones encontradas </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontraron direcciones </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Direccion>> findAll4WithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = findAll4ValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<Direccion>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtener direcciones (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Direcciones encontradas </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontraron direcciones </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call findAll4Async(final ApiCallback<List<Direccion>> _callback) throws ApiException {

        okhttp3.Call localVarCall = findAll4ValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<Direccion>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getDireccionById
     * @param id  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Dirección encontrada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontró la dirección </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getDireccionByIdCall(@javax.annotation.Nullable String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/direccion/get";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (id != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("id", id));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getDireccionByIdValidateBeforeCall(@javax.annotation.Nullable String id, final ApiCallback _callback) throws ApiException {
        return getDireccionByIdCall(id, _callback);

    }

    /**
     * 
     * 
     * @param id  (optional)
     * @return Direccion
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Dirección encontrada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontró la dirección </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public Direccion getDireccionById(@javax.annotation.Nullable String id) throws ApiException {
        ApiResponse<Direccion> localVarResp = getDireccionByIdWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id  (optional)
     * @return ApiResponse&lt;Direccion&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Dirección encontrada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontró la dirección </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Direccion> getDireccionByIdWithHttpInfo(@javax.annotation.Nullable String id) throws ApiException {
        okhttp3.Call localVarCall = getDireccionByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Direccion>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Dirección encontrada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontró la dirección </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getDireccionByIdAsync(@javax.annotation.Nullable String id, final ApiCallback<Direccion> _callback) throws ApiException {

        okhttp3.Call localVarCall = getDireccionByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Direccion>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getDireccionIDs
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Se han obtenido todos los IDs exitosamente </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado IDs </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getDireccionIDsCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/direccion/get/id";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getDireccionIDsValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getDireccionIDsCall(_callback);

    }

    /**
     * Obtener unicamente los ID de las direcciones
     * 
     * @return List&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Se han obtenido todos los IDs exitosamente </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado IDs </td><td>  -  </td></tr>
     </table>
     */
    public List<String> getDireccionIDs() throws ApiException {
        ApiResponse<List<String>> localVarResp = getDireccionIDsWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Obtener unicamente los ID de las direcciones
     * 
     * @return ApiResponse&lt;List&lt;String&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Se han obtenido todos los IDs exitosamente </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado IDs </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<String>> getDireccionIDsWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getDireccionIDsValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<String>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtener unicamente los ID de las direcciones (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Se han obtenido todos los IDs exitosamente </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado IDs </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getDireccionIDsAsync(final ApiCallback<List<String>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getDireccionIDsValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<String>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getDireccionOfRestaurante
     * @param restaurante  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Dirección encontrada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontró la dirección </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getDireccionOfRestauranteCall(@javax.annotation.Nullable String restaurante, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/direccion/getByRestaurante";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (restaurante != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("restaurante", restaurante));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getDireccionOfRestauranteValidateBeforeCall(@javax.annotation.Nullable String restaurante, final ApiCallback _callback) throws ApiException {
        return getDireccionOfRestauranteCall(restaurante, _callback);

    }

    /**
     * 
     * 
     * @param restaurante  (optional)
     * @return List&lt;Direccion&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Dirección encontrada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontró la dirección </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public List<Direccion> getDireccionOfRestaurante(@javax.annotation.Nullable String restaurante) throws ApiException {
        ApiResponse<List<Direccion>> localVarResp = getDireccionOfRestauranteWithHttpInfo(restaurante);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param restaurante  (optional)
     * @return ApiResponse&lt;List&lt;Direccion&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Dirección encontrada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontró la dirección </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Direccion>> getDireccionOfRestauranteWithHttpInfo(@javax.annotation.Nullable String restaurante) throws ApiException {
        okhttp3.Call localVarCall = getDireccionOfRestauranteValidateBeforeCall(restaurante, null);
        Type localVarReturnType = new TypeToken<List<Direccion>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param restaurante  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Dirección encontrada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontró la dirección </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getDireccionOfRestauranteAsync(@javax.annotation.Nullable String restaurante, final ApiCallback<List<Direccion>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getDireccionOfRestauranteValidateBeforeCall(restaurante, _callback);
        Type localVarReturnType = new TypeToken<List<Direccion>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getDireccionOfUser
     * @param user  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Dirección encontrada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontró la dirección </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getDireccionOfUserCall(@javax.annotation.Nullable String user, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/direccion/getByUser";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (user != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("user", user));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getDireccionOfUserValidateBeforeCall(@javax.annotation.Nullable String user, final ApiCallback _callback) throws ApiException {
        return getDireccionOfUserCall(user, _callback);

    }

    /**
     * 
     * 
     * @param user  (optional)
     * @return List&lt;Direccion&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Dirección encontrada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontró la dirección </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public List<Direccion> getDireccionOfUser(@javax.annotation.Nullable String user) throws ApiException {
        ApiResponse<List<Direccion>> localVarResp = getDireccionOfUserWithHttpInfo(user);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param user  (optional)
     * @return ApiResponse&lt;List&lt;Direccion&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Dirección encontrada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontró la dirección </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Direccion>> getDireccionOfUserWithHttpInfo(@javax.annotation.Nullable String user) throws ApiException {
        okhttp3.Call localVarCall = getDireccionOfUserValidateBeforeCall(user, null);
        Type localVarReturnType = new TypeToken<List<Direccion>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param user  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Dirección encontrada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se encontró la dirección </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getDireccionOfUserAsync(@javax.annotation.Nullable String user, final ApiCallback<List<Direccion>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getDireccionOfUserValidateBeforeCall(user, _callback);
        Type localVarReturnType = new TypeToken<List<Direccion>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for registerDireccion
     * @param direccion  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Registro exitoso. false: El registro ya existe o se produjo un error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call registerDireccionCall(@javax.annotation.Nonnull Direccion direccion, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = direccion;

        // create path and map variables
        String localVarPath = "/direccion/register";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call registerDireccionValidateBeforeCall(@javax.annotation.Nonnull Direccion direccion, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'direccion' is set
        if (direccion == null) {
            throw new ApiException("Missing the required parameter 'direccion' when calling registerDireccion(Async)");
        }

        return registerDireccionCall(direccion, _callback);

    }

    /**
     * Registrar una dirección
     * 
     * @param direccion  (required)
     * @return Direccion
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Registro exitoso. false: El registro ya existe o se produjo un error </td><td>  -  </td></tr>
     </table>
     */
    public Direccion registerDireccion(@javax.annotation.Nonnull Direccion direccion) throws ApiException {
        ApiResponse<Direccion> localVarResp = registerDireccionWithHttpInfo(direccion);
        return localVarResp.getData();
    }

    /**
     * Registrar una dirección
     * 
     * @param direccion  (required)
     * @return ApiResponse&lt;Direccion&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Registro exitoso. false: El registro ya existe o se produjo un error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Direccion> registerDireccionWithHttpInfo(@javax.annotation.Nonnull Direccion direccion) throws ApiException {
        okhttp3.Call localVarCall = registerDireccionValidateBeforeCall(direccion, null);
        Type localVarReturnType = new TypeToken<Direccion>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Registrar una dirección (asynchronously)
     * 
     * @param direccion  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Registro exitoso. false: El registro ya existe o se produjo un error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call registerDireccionAsync(@javax.annotation.Nonnull Direccion direccion, final ApiCallback<Direccion> _callback) throws ApiException {

        okhttp3.Call localVarCall = registerDireccionValidateBeforeCall(direccion, _callback);
        Type localVarReturnType = new TypeToken<Direccion>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateDireccion
     * @param direccion  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Actualization exitosa. false: El registro no existe o se produjo un error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateDireccionCall(@javax.annotation.Nonnull Direccion direccion, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = direccion;

        // create path and map variables
        String localVarPath = "/direccion/save";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateDireccionValidateBeforeCall(@javax.annotation.Nonnull Direccion direccion, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'direccion' is set
        if (direccion == null) {
            throw new ApiException("Missing the required parameter 'direccion' when calling updateDireccion(Async)");
        }

        return updateDireccionCall(direccion, _callback);

    }

    /**
     * Actualizar una dirección
     * 
     * @param direccion  (required)
     * @return Boolean
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Actualization exitosa. false: El registro no existe o se produjo un error </td><td>  -  </td></tr>
     </table>
     */
    public Boolean updateDireccion(@javax.annotation.Nonnull Direccion direccion) throws ApiException {
        ApiResponse<Boolean> localVarResp = updateDireccionWithHttpInfo(direccion);
        return localVarResp.getData();
    }

    /**
     * Actualizar una dirección
     * 
     * @param direccion  (required)
     * @return ApiResponse&lt;Boolean&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Actualization exitosa. false: El registro no existe o se produjo un error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Boolean> updateDireccionWithHttpInfo(@javax.annotation.Nonnull Direccion direccion) throws ApiException {
        okhttp3.Call localVarCall = updateDireccionValidateBeforeCall(direccion, null);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Actualizar una dirección (asynchronously)
     * 
     * @param direccion  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Actualization exitosa. false: El registro no existe o se produjo un error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateDireccionAsync(@javax.annotation.Nonnull Direccion direccion, final ApiCallback<Boolean> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateDireccionValidateBeforeCall(direccion, _callback);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
