/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.bomboplats.api;

import com.example.bomboplats.api.invoker.ApiCallback;
import com.example.bomboplats.api.invoker.ApiClient;
import com.example.bomboplats.api.invoker.ApiException;
import com.example.bomboplats.api.invoker.ApiResponse;
import com.example.bomboplats.api.invoker.Configuration;
import com.example.bomboplats.api.invoker.Pair;
import com.example.bomboplats.api.invoker.ProgressRequestBody;
import com.example.bomboplats.api.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.example.bomboplats.model.Pedido;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PedidoControllerApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PedidoControllerApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PedidoControllerApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deletePedido
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Pedido borrado. false: Ese registro no existe o se ha producido un error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deletePedidoCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/pedido/delete/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deletePedidoValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deletePedido(Async)");
        }

        return deletePedidoCall(id, _callback);

    }

    /**
     * Borrar un pedido
     * 
     * @param id  (required)
     * @return Boolean
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Pedido borrado. false: Ese registro no existe o se ha producido un error </td><td>  -  </td></tr>
     </table>
     */
    public Boolean deletePedido(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<Boolean> localVarResp = deletePedidoWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Borrar un pedido
     * 
     * @param id  (required)
     * @return ApiResponse&lt;Boolean&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Pedido borrado. false: Ese registro no existe o se ha producido un error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Boolean> deletePedidoWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = deletePedidoValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Borrar un pedido (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Pedido borrado. false: Ese registro no existe o se ha producido un error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deletePedidoAsync(@javax.annotation.Nonnull String id, final ApiCallback<Boolean> _callback) throws ApiException {

        okhttp3.Call localVarCall = deletePedidoValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for findAll3
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call findAll3Call(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/pedido/getAll";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call findAll3ValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return findAll3Call(_callback);

    }

    /**
     * Obtener todos los pedidos
     * 
     * @return List&lt;Pedido&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
     </table>
     */
    public List<Pedido> findAll3() throws ApiException {
        ApiResponse<List<Pedido>> localVarResp = findAll3WithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Obtener todos los pedidos
     * 
     * @return ApiResponse&lt;List&lt;Pedido&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Pedido>> findAll3WithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = findAll3ValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<Pedido>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtener todos los pedidos (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call findAll3Async(final ApiCallback<List<Pedido>> _callback) throws ApiException {

        okhttp3.Call localVarCall = findAll3ValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<Pedido>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPedidoByEstado
     * @param estado  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPedidoByEstadoCall(@javax.annotation.Nullable String estado, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/pedido/getByEstado";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (estado != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("estado", estado));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPedidoByEstadoValidateBeforeCall(@javax.annotation.Nullable String estado, final ApiCallback _callback) throws ApiException {
        return getPedidoByEstadoCall(estado, _callback);

    }

    /**
     * Obtener pedidos segun su estado
     * 
     * @param estado  (optional)
     * @return List&lt;Pedido&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public List<Pedido> getPedidoByEstado(@javax.annotation.Nullable String estado) throws ApiException {
        ApiResponse<List<Pedido>> localVarResp = getPedidoByEstadoWithHttpInfo(estado);
        return localVarResp.getData();
    }

    /**
     * Obtener pedidos segun su estado
     * 
     * @param estado  (optional)
     * @return ApiResponse&lt;List&lt;Pedido&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Pedido>> getPedidoByEstadoWithHttpInfo(@javax.annotation.Nullable String estado) throws ApiException {
        okhttp3.Call localVarCall = getPedidoByEstadoValidateBeforeCall(estado, null);
        Type localVarReturnType = new TypeToken<List<Pedido>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtener pedidos segun su estado (asynchronously)
     * 
     * @param estado  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPedidoByEstadoAsync(@javax.annotation.Nullable String estado, final ApiCallback<List<Pedido>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPedidoByEstadoValidateBeforeCall(estado, _callback);
        Type localVarReturnType = new TypeToken<List<Pedido>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPedidoById
     * @param id  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se ha encontrado el pedido </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPedidoByIdCall(@javax.annotation.Nullable String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/pedido/get";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (id != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("id", id));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPedidoByIdValidateBeforeCall(@javax.annotation.Nullable String id, final ApiCallback _callback) throws ApiException {
        return getPedidoByIdCall(id, _callback);

    }

    /**
     * Obtener un pedido segun su ID
     * 
     * @param id  (optional)
     * @return Pedido
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se ha encontrado el pedido </td><td>  -  </td></tr>
     </table>
     */
    public Pedido getPedidoById(@javax.annotation.Nullable String id) throws ApiException {
        ApiResponse<Pedido> localVarResp = getPedidoByIdWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Obtener un pedido segun su ID
     * 
     * @param id  (optional)
     * @return ApiResponse&lt;Pedido&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se ha encontrado el pedido </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Pedido> getPedidoByIdWithHttpInfo(@javax.annotation.Nullable String id) throws ApiException {
        okhttp3.Call localVarCall = getPedidoByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Pedido>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtener un pedido segun su ID (asynchronously)
     * 
     * @param id  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se ha encontrado el pedido </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPedidoByIdAsync(@javax.annotation.Nullable String id, final ApiCallback<Pedido> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPedidoByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Pedido>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPedidoByPlato
     * @param plato  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPedidoByPlatoCall(@javax.annotation.Nullable String plato, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/pedido/getByPlato";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (plato != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("plato", plato));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPedidoByPlatoValidateBeforeCall(@javax.annotation.Nullable String plato, final ApiCallback _callback) throws ApiException {
        return getPedidoByPlatoCall(plato, _callback);

    }

    /**
     * Obtener todos los pedidos que se han hecho de un plato según su id
     * 
     * @param plato  (optional)
     * @return List&lt;Pedido&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public List<Pedido> getPedidoByPlato(@javax.annotation.Nullable String plato) throws ApiException {
        ApiResponse<List<Pedido>> localVarResp = getPedidoByPlatoWithHttpInfo(plato);
        return localVarResp.getData();
    }

    /**
     * Obtener todos los pedidos que se han hecho de un plato según su id
     * 
     * @param plato  (optional)
     * @return ApiResponse&lt;List&lt;Pedido&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Pedido>> getPedidoByPlatoWithHttpInfo(@javax.annotation.Nullable String plato) throws ApiException {
        okhttp3.Call localVarCall = getPedidoByPlatoValidateBeforeCall(plato, null);
        Type localVarReturnType = new TypeToken<List<Pedido>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtener todos los pedidos que se han hecho de un plato según su id (asynchronously)
     * 
     * @param plato  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPedidoByPlatoAsync(@javax.annotation.Nullable String plato, final ApiCallback<List<Pedido>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPedidoByPlatoValidateBeforeCall(plato, _callback);
        Type localVarReturnType = new TypeToken<List<Pedido>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPedidoByUser
     * @param user  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrects </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPedidoByUserCall(@javax.annotation.Nullable String user, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/pedido/getByUser";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (user != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("user", user));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPedidoByUserValidateBeforeCall(@javax.annotation.Nullable String user, final ApiCallback _callback) throws ApiException {
        return getPedidoByUserCall(user, _callback);

    }

    /**
     * Obtener todos los pedidos de un usuario según su id
     * 
     * @param user  (optional)
     * @return List&lt;Pedido&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrects </td><td>  -  </td></tr>
     </table>
     */
    public List<Pedido> getPedidoByUser(@javax.annotation.Nullable String user) throws ApiException {
        ApiResponse<List<Pedido>> localVarResp = getPedidoByUserWithHttpInfo(user);
        return localVarResp.getData();
    }

    /**
     * Obtener todos los pedidos de un usuario según su id
     * 
     * @param user  (optional)
     * @return ApiResponse&lt;List&lt;Pedido&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrects </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Pedido>> getPedidoByUserWithHttpInfo(@javax.annotation.Nullable String user) throws ApiException {
        okhttp3.Call localVarCall = getPedidoByUserValidateBeforeCall(user, null);
        Type localVarReturnType = new TypeToken<List<Pedido>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtener todos los pedidos de un usuario según su id (asynchronously)
     * 
     * @param user  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Pedidos Encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado pedidos </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parametros incorrects </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPedidoByUserAsync(@javax.annotation.Nullable String user, final ApiCallback<List<Pedido>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPedidoByUserValidateBeforeCall(user, _callback);
        Type localVarReturnType = new TypeToken<List<Pedido>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPedidosIDs
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Se han obtenido todos los IDs exitosamente </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No hay ningun ID </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPedidosIDsCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/pedido/get/id";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPedidosIDsValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getPedidosIDsCall(_callback);

    }

    /**
     * Obtener unicamente el id de los pedidos
     * 
     * @return List&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Se han obtenido todos los IDs exitosamente </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No hay ningun ID </td><td>  -  </td></tr>
     </table>
     */
    public List<String> getPedidosIDs() throws ApiException {
        ApiResponse<List<String>> localVarResp = getPedidosIDsWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Obtener unicamente el id de los pedidos
     * 
     * @return ApiResponse&lt;List&lt;String&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Se han obtenido todos los IDs exitosamente </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No hay ningun ID </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<String>> getPedidosIDsWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getPedidosIDsValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<String>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtener unicamente el id de los pedidos (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Se han obtenido todos los IDs exitosamente </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No hay ningun ID </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPedidosIDsAsync(final ApiCallback<List<String>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPedidosIDsValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<String>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for register2
     * @param pedido  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Pedido registrado. false: Ese registro ya existe o se ha producido un error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call register2Call(@javax.annotation.Nonnull Pedido pedido, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = pedido;

        // create path and map variables
        String localVarPath = "/pedido/register";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call register2ValidateBeforeCall(@javax.annotation.Nonnull Pedido pedido, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'pedido' is set
        if (pedido == null) {
            throw new ApiException("Missing the required parameter 'pedido' when calling register2(Async)");
        }

        return register2Call(pedido, _callback);

    }

    /**
     * Registrar un pedido
     * 
     * @param pedido  (required)
     * @return Pedido
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Pedido registrado. false: Ese registro ya existe o se ha producido un error </td><td>  -  </td></tr>
     </table>
     */
    public Pedido register2(@javax.annotation.Nonnull Pedido pedido) throws ApiException {
        ApiResponse<Pedido> localVarResp = register2WithHttpInfo(pedido);
        return localVarResp.getData();
    }

    /**
     * Registrar un pedido
     * 
     * @param pedido  (required)
     * @return ApiResponse&lt;Pedido&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Pedido registrado. false: Ese registro ya existe o se ha producido un error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Pedido> register2WithHttpInfo(@javax.annotation.Nonnull Pedido pedido) throws ApiException {
        okhttp3.Call localVarCall = register2ValidateBeforeCall(pedido, null);
        Type localVarReturnType = new TypeToken<Pedido>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Registrar un pedido (asynchronously)
     * 
     * @param pedido  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Pedido registrado. false: Ese registro ya existe o se ha producido un error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call register2Async(@javax.annotation.Nonnull Pedido pedido, final ApiCallback<Pedido> _callback) throws ApiException {

        okhttp3.Call localVarCall = register2ValidateBeforeCall(pedido, _callback);
        Type localVarReturnType = new TypeToken<Pedido>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updatePedido
     * @param pedido  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Pedido actualizado. false: Ese registro no existe o se ha producido un error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updatePedidoCall(@javax.annotation.Nonnull Pedido pedido, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = pedido;

        // create path and map variables
        String localVarPath = "/pedido/save";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updatePedidoValidateBeforeCall(@javax.annotation.Nonnull Pedido pedido, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'pedido' is set
        if (pedido == null) {
            throw new ApiException("Missing the required parameter 'pedido' when calling updatePedido(Async)");
        }

        return updatePedidoCall(pedido, _callback);

    }

    /**
     * Actualizar un pedido
     * 
     * @param pedido  (required)
     * @return Boolean
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Pedido actualizado. false: Ese registro no existe o se ha producido un error </td><td>  -  </td></tr>
     </table>
     */
    public Boolean updatePedido(@javax.annotation.Nonnull Pedido pedido) throws ApiException {
        ApiResponse<Boolean> localVarResp = updatePedidoWithHttpInfo(pedido);
        return localVarResp.getData();
    }

    /**
     * Actualizar un pedido
     * 
     * @param pedido  (required)
     * @return ApiResponse&lt;Boolean&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Pedido actualizado. false: Ese registro no existe o se ha producido un error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Boolean> updatePedidoWithHttpInfo(@javax.annotation.Nonnull Pedido pedido) throws ApiException {
        okhttp3.Call localVarCall = updatePedidoValidateBeforeCall(pedido, null);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Actualizar un pedido (asynchronously)
     * 
     * @param pedido  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Pedido actualizado. false: Ese registro no existe o se ha producido un error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updatePedidoAsync(@javax.annotation.Nonnull Pedido pedido, final ApiCallback<Boolean> _callback) throws ApiException {

        okhttp3.Call localVarCall = updatePedidoValidateBeforeCall(pedido, _callback);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
