/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.bomboplats.api;

import com.example.bomboplats.api.invoker.ApiCallback;
import com.example.bomboplats.api.invoker.ApiClient;
import com.example.bomboplats.api.invoker.ApiException;
import com.example.bomboplats.api.invoker.ApiResponse;
import com.example.bomboplats.api.invoker.Configuration;
import com.example.bomboplats.api.invoker.Pair;
import com.example.bomboplats.api.invoker.ProgressRequestBody;
import com.example.bomboplats.api.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.example.bomboplats.model.Plato;
import com.example.bomboplats.model.Restaurante;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RestauranteControllerApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public RestauranteControllerApi() {
        this(Configuration.getDefaultApiClient());
    }

    public RestauranteControllerApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deleteRestaurante
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Restaurante eliminado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteRestauranteCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/restaurante/delete/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteRestauranteValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteRestaurante(Async)");
        }

        return deleteRestauranteCall(id, _callback);

    }

    /**
     * Eliminar un restaurante
     * 
     * @param id  (required)
     * @return Boolean
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Restaurante eliminado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public Boolean deleteRestaurante(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<Boolean> localVarResp = deleteRestauranteWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Eliminar un restaurante
     * 
     * @param id  (required)
     * @return ApiResponse&lt;Boolean&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Restaurante eliminado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Boolean> deleteRestauranteWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = deleteRestauranteValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Eliminar un restaurante (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Restaurante eliminado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteRestauranteAsync(@javax.annotation.Nonnull String id, final ApiCallback<Boolean> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteRestauranteValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for findAll1
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call findAll1Call(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/restaurante/getAll";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call findAll1ValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return findAll1Call(_callback);

    }

    /**
     * Obtener todos los restaurantes
     * 
     * @return List&lt;Restaurante&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public List<Restaurante> findAll1() throws ApiException {
        ApiResponse<List<Restaurante>> localVarResp = findAll1WithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Obtener todos los restaurantes
     * 
     * @return ApiResponse&lt;List&lt;Restaurante&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Restaurante>> findAll1WithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = findAll1ValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<Restaurante>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtener todos los restaurantes (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call findAll1Async(final ApiCallback<List<Restaurante>> _callback) throws ApiException {

        okhttp3.Call localVarCall = findAll1ValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<Restaurante>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getByDescription
     * @param description  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByDescriptionCall(@javax.annotation.Nonnull String description, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/restaurante/getporescription";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (description != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("description", description));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getByDescriptionValidateBeforeCall(@javax.annotation.Nonnull String description, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'description' is set
        if (description == null) {
            throw new ApiException("Missing the required parameter 'description' when calling getByDescription(Async)");
        }

        return getByDescriptionCall(description, _callback);

    }

    /**
     * Buscar restaurantes por descripción
     * 
     * @param description  (required)
     * @return List&lt;Restaurante&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public List<Restaurante> getByDescription(@javax.annotation.Nonnull String description) throws ApiException {
        ApiResponse<List<Restaurante>> localVarResp = getByDescriptionWithHttpInfo(description);
        return localVarResp.getData();
    }

    /**
     * Buscar restaurantes por descripción
     * 
     * @param description  (required)
     * @return ApiResponse&lt;List&lt;Restaurante&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Restaurante>> getByDescriptionWithHttpInfo(@javax.annotation.Nonnull String description) throws ApiException {
        okhttp3.Call localVarCall = getByDescriptionValidateBeforeCall(description, null);
        Type localVarReturnType = new TypeToken<List<Restaurante>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Buscar restaurantes por descripción (asynchronously)
     * 
     * @param description  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByDescriptionAsync(@javax.annotation.Nonnull String description, final ApiCallback<List<Restaurante>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getByDescriptionValidateBeforeCall(description, _callback);
        Type localVarReturnType = new TypeToken<List<Restaurante>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getByNombre
     * @param nombre  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByNombreCall(@javax.annotation.Nonnull String nombre, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/restaurante/getpornombre";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (nombre != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("nombre", nombre));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getByNombreValidateBeforeCall(@javax.annotation.Nonnull String nombre, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'nombre' is set
        if (nombre == null) {
            throw new ApiException("Missing the required parameter 'nombre' when calling getByNombre(Async)");
        }

        return getByNombreCall(nombre, _callback);

    }

    /**
     * Buscar restaurantes por nombre
     * 
     * @param nombre  (required)
     * @return List&lt;Restaurante&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public List<Restaurante> getByNombre(@javax.annotation.Nonnull String nombre) throws ApiException {
        ApiResponse<List<Restaurante>> localVarResp = getByNombreWithHttpInfo(nombre);
        return localVarResp.getData();
    }

    /**
     * Buscar restaurantes por nombre
     * 
     * @param nombre  (required)
     * @return ApiResponse&lt;List&lt;Restaurante&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Restaurante>> getByNombreWithHttpInfo(@javax.annotation.Nonnull String nombre) throws ApiException {
        okhttp3.Call localVarCall = getByNombreValidateBeforeCall(nombre, null);
        Type localVarReturnType = new TypeToken<List<Restaurante>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Buscar restaurantes por nombre (asynchronously)
     * 
     * @param nombre  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByNombreAsync(@javax.annotation.Nonnull String nombre, final ApiCallback<List<Restaurante>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getByNombreValidateBeforeCall(nombre, _callback);
        Type localVarReturnType = new TypeToken<List<Restaurante>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getByTag
     * @param tag  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByTagCall(@javax.annotation.Nonnull String tag, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/restaurante/getportag";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (tag != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("tag", tag));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getByTagValidateBeforeCall(@javax.annotation.Nonnull String tag, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'tag' is set
        if (tag == null) {
            throw new ApiException("Missing the required parameter 'tag' when calling getByTag(Async)");
        }

        return getByTagCall(tag, _callback);

    }

    /**
     * Buscar restaurantes por tag
     * 
     * @param tag  (required)
     * @return List&lt;Restaurante&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public List<Restaurante> getByTag(@javax.annotation.Nonnull String tag) throws ApiException {
        ApiResponse<List<Restaurante>> localVarResp = getByTagWithHttpInfo(tag);
        return localVarResp.getData();
    }

    /**
     * Buscar restaurantes por tag
     * 
     * @param tag  (required)
     * @return ApiResponse&lt;List&lt;Restaurante&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Restaurante>> getByTagWithHttpInfo(@javax.annotation.Nonnull String tag) throws ApiException {
        okhttp3.Call localVarCall = getByTagValidateBeforeCall(tag, null);
        Type localVarReturnType = new TypeToken<List<Restaurante>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Buscar restaurantes por tag (asynchronously)
     * 
     * @param tag  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurantes encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado restaurantes </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByTagAsync(@javax.annotation.Nonnull String tag, final ApiCallback<List<Restaurante>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getByTagValidateBeforeCall(tag, _callback);
        Type localVarReturnType = new TypeToken<List<Restaurante>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getRestauranteById
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurante encontrado </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se ha encontrado el restaurante </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parámetros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRestauranteByIdCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/restaurante/get/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getRestauranteByIdValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getRestauranteById(Async)");
        }

        return getRestauranteByIdCall(id, _callback);

    }

    /**
     * Obtener restaurante por ID
     * 
     * @param id  (required)
     * @return Restaurante
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurante encontrado </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se ha encontrado el restaurante </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parámetros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public Restaurante getRestauranteById(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<Restaurante> localVarResp = getRestauranteByIdWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Obtener restaurante por ID
     * 
     * @param id  (required)
     * @return ApiResponse&lt;Restaurante&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurante encontrado </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se ha encontrado el restaurante </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parámetros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Restaurante> getRestauranteByIdWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = getRestauranteByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Restaurante>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtener restaurante por ID (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurante encontrado </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se ha encontrado el restaurante </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parámetros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRestauranteByIdAsync(@javax.annotation.Nonnull String id, final ApiCallback<Restaurante> _callback) throws ApiException {

        okhttp3.Call localVarCall = getRestauranteByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Restaurante>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getRestauranteIconUploadUrl
     * @param id  (required)
     * @param index  (optional, default to 0)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> URL generada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Restaurante no encontrado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRestauranteIconUploadUrlCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer index, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/restaurante/icon-upload-url/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (index != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("index", index));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getRestauranteIconUploadUrlValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer index, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getRestauranteIconUploadUrl(Async)");
        }

        return getRestauranteIconUploadUrlCall(id, index, _callback);

    }

    /**
     * Obtener URL prefirmada para subir foto de restaurante
     * 
     * @param id  (required)
     * @param index  (optional, default to 0)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> URL generada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Restaurante no encontrado </td><td>  -  </td></tr>
     </table>
     */
    public String getRestauranteIconUploadUrl(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer index) throws ApiException {
        ApiResponse<String> localVarResp = getRestauranteIconUploadUrlWithHttpInfo(id, index);
        return localVarResp.getData();
    }

    /**
     * Obtener URL prefirmada para subir foto de restaurante
     * 
     * @param id  (required)
     * @param index  (optional, default to 0)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> URL generada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Restaurante no encontrado </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> getRestauranteIconUploadUrlWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer index) throws ApiException {
        okhttp3.Call localVarCall = getRestauranteIconUploadUrlValidateBeforeCall(id, index, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtener URL prefirmada para subir foto de restaurante (asynchronously)
     * 
     * @param id  (required)
     * @param index  (optional, default to 0)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> URL generada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Restaurante no encontrado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRestauranteIconUploadUrlAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer index, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = getRestauranteIconUploadUrlValidateBeforeCall(id, index, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for register
     * @param restaurante  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurante registrado con su ID generado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call registerCall(@javax.annotation.Nonnull Restaurante restaurante, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = restaurante;

        // create path and map variables
        String localVarPath = "/restaurante/register";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call registerValidateBeforeCall(@javax.annotation.Nonnull Restaurante restaurante, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'restaurante' is set
        if (restaurante == null) {
            throw new ApiException("Missing the required parameter 'restaurante' when calling register(Async)");
        }

        return registerCall(restaurante, _callback);

    }

    /**
     * Registrar un restaurante
     * 
     * @param restaurante  (required)
     * @return Restaurante
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurante registrado con su ID generado </td><td>  -  </td></tr>
     </table>
     */
    public Restaurante register(@javax.annotation.Nonnull Restaurante restaurante) throws ApiException {
        ApiResponse<Restaurante> localVarResp = registerWithHttpInfo(restaurante);
        return localVarResp.getData();
    }

    /**
     * Registrar un restaurante
     * 
     * @param restaurante  (required)
     * @return ApiResponse&lt;Restaurante&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurante registrado con su ID generado </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Restaurante> registerWithHttpInfo(@javax.annotation.Nonnull Restaurante restaurante) throws ApiException {
        okhttp3.Call localVarCall = registerValidateBeforeCall(restaurante, null);
        Type localVarReturnType = new TypeToken<Restaurante>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Registrar un restaurante (asynchronously)
     * 
     * @param restaurante  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Restaurante registrado con su ID generado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call registerAsync(@javax.annotation.Nonnull Restaurante restaurante, final ApiCallback<Restaurante> _callback) throws ApiException {

        okhttp3.Call localVarCall = registerValidateBeforeCall(restaurante, _callback);
        Type localVarReturnType = new TypeToken<Restaurante>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for registerPlato
     * @param idRestaurante  (required)
     * @param plato  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Plato registrado con su ID generado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call registerPlatoCall(@javax.annotation.Nonnull String idRestaurante, @javax.annotation.Nonnull Plato plato, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = plato;

        // create path and map variables
        String localVarPath = "/restaurante/{idRestaurante}/plato/register"
            .replace("{" + "idRestaurante" + "}", localVarApiClient.escapeString(idRestaurante.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call registerPlatoValidateBeforeCall(@javax.annotation.Nonnull String idRestaurante, @javax.annotation.Nonnull Plato plato, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idRestaurante' is set
        if (idRestaurante == null) {
            throw new ApiException("Missing the required parameter 'idRestaurante' when calling registerPlato(Async)");
        }

        // verify the required parameter 'plato' is set
        if (plato == null) {
            throw new ApiException("Missing the required parameter 'plato' when calling registerPlato(Async)");
        }

        return registerPlatoCall(idRestaurante, plato, _callback);

    }

    /**
     * Registrar un plato asociado a un restaurante
     * 
     * @param idRestaurante  (required)
     * @param plato  (required)
     * @return Plato
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Plato registrado con su ID generado </td><td>  -  </td></tr>
     </table>
     */
    public Plato registerPlato(@javax.annotation.Nonnull String idRestaurante, @javax.annotation.Nonnull Plato plato) throws ApiException {
        ApiResponse<Plato> localVarResp = registerPlatoWithHttpInfo(idRestaurante, plato);
        return localVarResp.getData();
    }

    /**
     * Registrar un plato asociado a un restaurante
     * 
     * @param idRestaurante  (required)
     * @param plato  (required)
     * @return ApiResponse&lt;Plato&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Plato registrado con su ID generado </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Plato> registerPlatoWithHttpInfo(@javax.annotation.Nonnull String idRestaurante, @javax.annotation.Nonnull Plato plato) throws ApiException {
        okhttp3.Call localVarCall = registerPlatoValidateBeforeCall(idRestaurante, plato, null);
        Type localVarReturnType = new TypeToken<Plato>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Registrar un plato asociado a un restaurante (asynchronously)
     * 
     * @param idRestaurante  (required)
     * @param plato  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Plato registrado con su ID generado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call registerPlatoAsync(@javax.annotation.Nonnull String idRestaurante, @javax.annotation.Nonnull Plato plato, final ApiCallback<Plato> _callback) throws ApiException {

        okhttp3.Call localVarCall = registerPlatoValidateBeforeCall(idRestaurante, plato, _callback);
        Type localVarReturnType = new TypeToken<Plato>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateRestaurante
     * @param restaurante  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Restaurante actualizado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateRestauranteCall(@javax.annotation.Nonnull Restaurante restaurante, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = restaurante;

        // create path and map variables
        String localVarPath = "/restaurante/save";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateRestauranteValidateBeforeCall(@javax.annotation.Nonnull Restaurante restaurante, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'restaurante' is set
        if (restaurante == null) {
            throw new ApiException("Missing the required parameter 'restaurante' when calling updateRestaurante(Async)");
        }

        return updateRestauranteCall(restaurante, _callback);

    }

    /**
     * Actualizar un restaurante
     * 
     * @param restaurante  (required)
     * @return Boolean
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Restaurante actualizado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public Boolean updateRestaurante(@javax.annotation.Nonnull Restaurante restaurante) throws ApiException {
        ApiResponse<Boolean> localVarResp = updateRestauranteWithHttpInfo(restaurante);
        return localVarResp.getData();
    }

    /**
     * Actualizar un restaurante
     * 
     * @param restaurante  (required)
     * @return ApiResponse&lt;Boolean&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Restaurante actualizado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Boolean> updateRestauranteWithHttpInfo(@javax.annotation.Nonnull Restaurante restaurante) throws ApiException {
        okhttp3.Call localVarCall = updateRestauranteValidateBeforeCall(restaurante, null);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Actualizar un restaurante (asynchronously)
     * 
     * @param restaurante  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Restaurante actualizado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateRestauranteAsync(@javax.annotation.Nonnull Restaurante restaurante, final ApiCallback<Boolean> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateRestauranteValidateBeforeCall(restaurante, _callback);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
