/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.bomboplats.api;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Direccion
 */
public class DireccionTest {
    private final Direccion model = new Direccion();

    /**
     * Model tests for Direccion
     */
    @Test
    public void testDireccion() {
        // TODO: test Direccion
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'poblacion'
     */
    @Test
    public void poblacionTest() {
        // TODO: test poblacion
    }

    /**
     * Test the property 'codigoPostal'
     */
    @Test
    public void codigoPostalTest() {
        // TODO: test codigoPostal
    }

    /**
     * Test the property 'calle'
     */
    @Test
    public void calleTest() {
        // TODO: test calle
    }

    /**
     * Test the property 'portal'
     */
    @Test
    public void portalTest() {
        // TODO: test portal
    }

    /**
     * Test the property 'piso'
     */
    @Test
    public void pisoTest() {
        // TODO: test piso
    }

}
