/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.bomboplats.api;

import com.example.bomboplats.api.ApiException;
import com.example.bomboplats.api.Direccion;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DireccionControllerApi
 */
@Disabled
public class DireccionControllerApiTest {

    private final DireccionControllerApi api = new DireccionControllerApi();

    /**
     * Borrar una dirección por su Id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteByIdTest() throws ApiException {
        String id = null;
        Boolean response = api.deleteById(id);
        // TODO: test validations
    }

    /**
     * Obtener direcciones
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findAll4Test() throws ApiException {
        List<Direccion> response = api.findAll4();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDireccionByIdTest() throws ApiException {
        String id = null;
        Direccion response = api.getDireccionById(id);
        // TODO: test validations
    }

    /**
     * Obtener unicamente los ID de las direcciones
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDireccionIDsTest() throws ApiException {
        List<String> response = api.getDireccionIDs();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDireccionOfRestauranteTest() throws ApiException {
        String restaurante = null;
        List<Direccion> response = api.getDireccionOfRestaurante(restaurante);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDireccionOfUserTest() throws ApiException {
        String user = null;
        List<Direccion> response = api.getDireccionOfUser(user);
        // TODO: test validations
    }

    /**
     * Registrar una dirección
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registerDireccionTest() throws ApiException {
        Direccion direccion = null;
        Direccion response = api.registerDireccion(direccion);
        // TODO: test validations
    }

    /**
     * Actualizar una dirección
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateDireccionTest() throws ApiException {
        Direccion direccion = null;
        Boolean response = api.updateDireccion(direccion);
        // TODO: test validations
    }

}
