/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.bomboplats.api;

import com.example.bomboplats.api.Plato;
import com.example.bomboplats.api.User;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Pedido
 */
public class PedidoTest {
    private final Pedido model = new Pedido();

    /**
     * Model tests for Pedido
     */
    @Test
    public void testPedido() {
        // TODO: test Pedido
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'plato'
     */
    @Test
    public void platoTest() {
        // TODO: test plato
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'modifications'
     */
    @Test
    public void modificationsTest() {
        // TODO: test modifications
    }

    /**
     * Test the property 'estado'
     */
    @Test
    public void estadoTest() {
        // TODO: test estado
    }

    /**
     * Test the property 'entrega'
     */
    @Test
    public void entregaTest() {
        // TODO: test entrega
    }

}
