/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.bomboplats.api;

import com.example.bomboplats.api.ApiException;
import com.example.bomboplats.api.Plato;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlatoControllerApi
 */
@Disabled
public class PlatoControllerApiTest {

    private final PlatoControllerApi api = new PlatoControllerApi();

    /**
     * Eliminar un plato por su ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePlatoTest() throws ApiException {
        String id = null;
        Boolean response = api.deletePlato(id);
        // TODO: test validations
    }

    /**
     * Obtener todos los platos
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findAll2Test() throws ApiException {
        List<Plato> response = api.findAll2();
        // TODO: test validations
    }

    /**
     * Buscar platos por nombre
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByNombre1Test() throws ApiException {
        String nombre = null;
        List<Plato> response = api.getByNombre1(nombre);
        // TODO: test validations
    }

    /**
     * Buscar platos por ID de restaurante
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByRestauranteTest() throws ApiException {
        String idRestaurante = null;
        List<Plato> response = api.getByRestaurante(idRestaurante);
        // TODO: test validations
    }

    /**
     * Buscar platos por restaurante y nombre
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByRestauranteAndNombreTest() throws ApiException {
        String idRestaurante = null;
        String nombre = null;
        List<Plato> response = api.getByRestauranteAndNombre(idRestaurante, nombre);
        // TODO: test validations
    }

    /**
     * Buscar platos por tag
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByTag1Test() throws ApiException {
        String tag = null;
        List<Plato> response = api.getByTag1(tag);
        // TODO: test validations
    }

    /**
     * Obtener un plato por su ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPlatoByIdTest() throws ApiException {
        String id = null;
        Plato response = api.getPlatoById(id);
        // TODO: test validations
    }

    /**
     * Obtener URL prefirmada para subir foto de plato
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPlatoIconUploadUrlTest() throws ApiException {
        String id = null;
        String response = api.getPlatoIconUploadUrl(id);
        // TODO: test validations
    }

    /**
     * Registrar un nuevo plato
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void register1Test() throws ApiException {
        Plato plato = null;
        Plato response = api.register1(plato);
        // TODO: test validations
    }

    /**
     * Actualizar un plato existente
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePlatoTest() throws ApiException {
        Plato plato = null;
        Boolean response = api.updatePlato(plato);
        // TODO: test validations
    }

}
