/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.bomboplats.api;

import com.example.bomboplats.api.ApiException;
import com.example.bomboplats.api.Plato;
import com.example.bomboplats.api.Restaurante;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RestauranteControllerApi
 */
@Disabled
public class RestauranteControllerApiTest {

    private final RestauranteControllerApi api = new RestauranteControllerApi();

    /**
     * Eliminar un restaurante
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteRestauranteTest() throws ApiException {
        String id = null;
        Boolean response = api.deleteRestaurante(id);
        // TODO: test validations
    }

    /**
     * Obtener todos los restaurantes
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findAll1Test() throws ApiException {
        List<Restaurante> response = api.findAll1();
        // TODO: test validations
    }

    /**
     * Buscar restaurantes por descripción
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByDescriptionTest() throws ApiException {
        String description = null;
        List<Restaurante> response = api.getByDescription(description);
        // TODO: test validations
    }

    /**
     * Buscar restaurantes por nombre
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByNombreTest() throws ApiException {
        String nombre = null;
        List<Restaurante> response = api.getByNombre(nombre);
        // TODO: test validations
    }

    /**
     * Buscar restaurantes por tag
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByTagTest() throws ApiException {
        String tag = null;
        List<Restaurante> response = api.getByTag(tag);
        // TODO: test validations
    }

    /**
     * Obtener restaurante por ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRestauranteByIdTest() throws ApiException {
        String id = null;
        Restaurante response = api.getRestauranteById(id);
        // TODO: test validations
    }

    /**
     * Obtener URL prefirmada para subir foto de restaurante
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRestauranteIconUploadUrlTest() throws ApiException {
        String id = null;
        Integer index = null;
        String response = api.getRestauranteIconUploadUrl(id, index);
        // TODO: test validations
    }

    /**
     * Registrar un restaurante
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registerTest() throws ApiException {
        Restaurante restaurante = null;
        Restaurante response = api.register(restaurante);
        // TODO: test validations
    }

    /**
     * Registrar un plato asociado a un restaurante
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registerPlatoTest() throws ApiException {
        String idRestaurante = null;
        Plato plato = null;
        Plato response = api.registerPlato(idRestaurante, plato);
        // TODO: test validations
    }

    /**
     * Actualizar un restaurante
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateRestauranteTest() throws ApiException {
        Restaurante restaurante = null;
        Boolean response = api.updateRestaurante(restaurante);
        // TODO: test validations
    }

}
