/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.bomboplats.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.example.bomboplats.api.JSON;

/**
 * Direccion
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-07T19:05:09.591510200+02:00[Europe/Madrid]", comments = "Generator version: 7.21.0")
public class Direccion {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_POBLACION = "poblacion";
  @SerializedName(SERIALIZED_NAME_POBLACION)
  @javax.annotation.Nullable
  private String poblacion;

  public static final String SERIALIZED_NAME_CODIGO_POSTAL = "codigoPostal";
  @SerializedName(SERIALIZED_NAME_CODIGO_POSTAL)
  @javax.annotation.Nullable
  private String codigoPostal;

  public static final String SERIALIZED_NAME_CALLE = "calle";
  @SerializedName(SERIALIZED_NAME_CALLE)
  @javax.annotation.Nullable
  private String calle;

  public static final String SERIALIZED_NAME_PORTAL = "portal";
  @SerializedName(SERIALIZED_NAME_PORTAL)
  @javax.annotation.Nullable
  private Integer portal;

  public static final String SERIALIZED_NAME_PISO = "piso";
  @SerializedName(SERIALIZED_NAME_PISO)
  @javax.annotation.Nullable
  private String piso;

  public Direccion() {
  }

  public Direccion id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public Direccion poblacion(@javax.annotation.Nullable String poblacion) {
    this.poblacion = poblacion;
    return this;
  }

  /**
   * Get poblacion
   * @return poblacion
   */
  @javax.annotation.Nullable
  public String getPoblacion() {
    return poblacion;
  }

  public void setPoblacion(@javax.annotation.Nullable String poblacion) {
    this.poblacion = poblacion;
  }


  public Direccion codigoPostal(@javax.annotation.Nullable String codigoPostal) {
    this.codigoPostal = codigoPostal;
    return this;
  }

  /**
   * Get codigoPostal
   * @return codigoPostal
   */
  @javax.annotation.Nullable
  public String getCodigoPostal() {
    return codigoPostal;
  }

  public void setCodigoPostal(@javax.annotation.Nullable String codigoPostal) {
    this.codigoPostal = codigoPostal;
  }


  public Direccion calle(@javax.annotation.Nullable String calle) {
    this.calle = calle;
    return this;
  }

  /**
   * Get calle
   * @return calle
   */
  @javax.annotation.Nullable
  public String getCalle() {
    return calle;
  }

  public void setCalle(@javax.annotation.Nullable String calle) {
    this.calle = calle;
  }


  public Direccion portal(@javax.annotation.Nullable Integer portal) {
    this.portal = portal;
    return this;
  }

  /**
   * Get portal
   * @return portal
   */
  @javax.annotation.Nullable
  public Integer getPortal() {
    return portal;
  }

  public void setPortal(@javax.annotation.Nullable Integer portal) {
    this.portal = portal;
  }


  public Direccion piso(@javax.annotation.Nullable String piso) {
    this.piso = piso;
    return this;
  }

  /**
   * Get piso
   * @return piso
   */
  @javax.annotation.Nullable
  public String getPiso() {
    return piso;
  }

  public void setPiso(@javax.annotation.Nullable String piso) {
    this.piso = piso;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Direccion direccion = (Direccion) o;
    return Objects.equals(this.id, direccion.id) &&
        Objects.equals(this.poblacion, direccion.poblacion) &&
        Objects.equals(this.codigoPostal, direccion.codigoPostal) &&
        Objects.equals(this.calle, direccion.calle) &&
        Objects.equals(this.portal, direccion.portal) &&
        Objects.equals(this.piso, direccion.piso);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, poblacion, codigoPostal, calle, portal, piso);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Direccion {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    poblacion: ").append(toIndentedString(poblacion)).append("\n");
    sb.append("    codigoPostal: ").append(toIndentedString(codigoPostal)).append("\n");
    sb.append("    calle: ").append(toIndentedString(calle)).append("\n");
    sb.append("    portal: ").append(toIndentedString(portal)).append("\n");
    sb.append("    piso: ").append(toIndentedString(piso)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "poblacion", "codigoPostal", "calle", "portal", "piso"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Direccion
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Direccion.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Direccion is not found in the empty JSON string", Direccion.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Direccion.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Direccion` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("poblacion") != null && !jsonObj.get("poblacion").isJsonNull()) && !jsonObj.get("poblacion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `poblacion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("poblacion").toString()));
      }
      if ((jsonObj.get("codigoPostal") != null && !jsonObj.get("codigoPostal").isJsonNull()) && !jsonObj.get("codigoPostal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `codigoPostal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("codigoPostal").toString()));
      }
      if ((jsonObj.get("calle") != null && !jsonObj.get("calle").isJsonNull()) && !jsonObj.get("calle").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `calle` to be a primitive type in the JSON string but got `%s`", jsonObj.get("calle").toString()));
      }
      if ((jsonObj.get("piso") != null && !jsonObj.get("piso").isJsonNull()) && !jsonObj.get("piso").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `piso` to be a primitive type in the JSON string but got `%s`", jsonObj.get("piso").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Direccion.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Direccion' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Direccion> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Direccion.class));

       return (TypeAdapter<T>) new TypeAdapter<Direccion>() {
           @Override
           public void write(JsonWriter out, Direccion value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Direccion read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Direccion given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Direccion
   * @throws IOException if the JSON string is invalid with respect to Direccion
   */
  public static Direccion fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Direccion.class);
  }

  /**
   * Convert an instance of Direccion to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

