/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.bomboplats.api;

import java.util.Objects;
import com.example.bomboplats.api.Plato;
import com.example.bomboplats.api.User;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.example.bomboplats.api.JSON;

/**
 * Pedido
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-07T19:05:09.591510200+02:00[Europe/Madrid]", comments = "Generator version: 7.21.0")
public class Pedido {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_PLATO = "plato";
  @SerializedName(SERIALIZED_NAME_PLATO)
  @javax.annotation.Nullable
  private Plato plato;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  @javax.annotation.Nullable
  private User user;

  public static final String SERIALIZED_NAME_MODIFICATIONS = "modifications";
  @SerializedName(SERIALIZED_NAME_MODIFICATIONS)
  @javax.annotation.Nullable
  private List<String> modifications = new ArrayList<>();

  /**
   * Gets or Sets estado
   */
  @JsonAdapter(EstadoEnum.Adapter.class)
  public enum EstadoEnum {
    PREPARING("PREPARING"),
    
    DELIVERING("DELIVERING"),
    
    DELIVERED("DELIVERED");

    private String value;

    EstadoEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EstadoEnum fromValue(String value) {
      for (EstadoEnum b : EstadoEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<EstadoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EstadoEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EstadoEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return EstadoEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      EstadoEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ESTADO = "estado";
  @SerializedName(SERIALIZED_NAME_ESTADO)
  @javax.annotation.Nullable
  private EstadoEnum estado;

  public static final String SERIALIZED_NAME_ENTREGA = "entrega";
  @SerializedName(SERIALIZED_NAME_ENTREGA)
  @javax.annotation.Nullable
  private OffsetDateTime entrega;

  public Pedido() {
  }

  public Pedido id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public Pedido plato(@javax.annotation.Nullable Plato plato) {
    this.plato = plato;
    return this;
  }

  /**
   * Get plato
   * @return plato
   */
  @javax.annotation.Nullable
  public Plato getPlato() {
    return plato;
  }

  public void setPlato(@javax.annotation.Nullable Plato plato) {
    this.plato = plato;
  }


  public Pedido user(@javax.annotation.Nullable User user) {
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @javax.annotation.Nullable
  public User getUser() {
    return user;
  }

  public void setUser(@javax.annotation.Nullable User user) {
    this.user = user;
  }


  public Pedido modifications(@javax.annotation.Nullable List<String> modifications) {
    this.modifications = modifications;
    return this;
  }

  public Pedido addModificationsItem(String modificationsItem) {
    if (this.modifications == null) {
      this.modifications = new ArrayList<>();
    }
    this.modifications.add(modificationsItem);
    return this;
  }

  /**
   * Get modifications
   * @return modifications
   */
  @javax.annotation.Nullable
  public List<String> getModifications() {
    return modifications;
  }

  public void setModifications(@javax.annotation.Nullable List<String> modifications) {
    this.modifications = modifications;
  }


  public Pedido estado(@javax.annotation.Nullable EstadoEnum estado) {
    this.estado = estado;
    return this;
  }

  /**
   * Get estado
   * @return estado
   */
  @javax.annotation.Nullable
  public EstadoEnum getEstado() {
    return estado;
  }

  public void setEstado(@javax.annotation.Nullable EstadoEnum estado) {
    this.estado = estado;
  }


  public Pedido entrega(@javax.annotation.Nullable OffsetDateTime entrega) {
    this.entrega = entrega;
    return this;
  }

  /**
   * Get entrega
   * @return entrega
   */
  @javax.annotation.Nullable
  public OffsetDateTime getEntrega() {
    return entrega;
  }

  public void setEntrega(@javax.annotation.Nullable OffsetDateTime entrega) {
    this.entrega = entrega;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pedido pedido = (Pedido) o;
    return Objects.equals(this.id, pedido.id) &&
        Objects.equals(this.plato, pedido.plato) &&
        Objects.equals(this.user, pedido.user) &&
        Objects.equals(this.modifications, pedido.modifications) &&
        Objects.equals(this.estado, pedido.estado) &&
        Objects.equals(this.entrega, pedido.entrega);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, plato, user, modifications, estado, entrega);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pedido {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    plato: ").append(toIndentedString(plato)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    modifications: ").append(toIndentedString(modifications)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    entrega: ").append(toIndentedString(entrega)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "plato", "user", "modifications", "estado", "entrega"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Pedido
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Pedido.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Pedido is not found in the empty JSON string", Pedido.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Pedido.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Pedido` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // validate the optional field `plato`
      if (jsonObj.get("plato") != null && !jsonObj.get("plato").isJsonNull()) {
        Plato.validateJsonElement(jsonObj.get("plato"));
      }
      // validate the optional field `user`
      if (jsonObj.get("user") != null && !jsonObj.get("user").isJsonNull()) {
        User.validateJsonElement(jsonObj.get("user"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("modifications") != null && !jsonObj.get("modifications").isJsonNull() && !jsonObj.get("modifications").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `modifications` to be an array in the JSON string but got `%s`", jsonObj.get("modifications").toString()));
      }
      if ((jsonObj.get("estado") != null && !jsonObj.get("estado").isJsonNull()) && !jsonObj.get("estado").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `estado` to be a primitive type in the JSON string but got `%s`", jsonObj.get("estado").toString()));
      }
      // validate the optional field `estado`
      if (jsonObj.get("estado") != null && !jsonObj.get("estado").isJsonNull()) {
        EstadoEnum.validateJsonElement(jsonObj.get("estado"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Pedido.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Pedido' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Pedido> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Pedido.class));

       return (TypeAdapter<T>) new TypeAdapter<Pedido>() {
           @Override
           public void write(JsonWriter out, Pedido value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Pedido read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Pedido given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Pedido
   * @throws IOException if the JSON string is invalid with respect to Pedido
   */
  public static Pedido fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Pedido.class);
  }

  /**
   * Convert an instance of Pedido to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

