/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.bomboplats.api;

import com.example.bomboplats.api.ApiCallback;
import com.example.bomboplats.api.ApiClient;
import com.example.bomboplats.api.ApiException;
import com.example.bomboplats.api.ApiResponse;
import com.example.bomboplats.api.Configuration;
import com.example.bomboplats.api.Pair;
import com.example.bomboplats.api.ProgressRequestBody;
import com.example.bomboplats.api.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.example.bomboplats.api.Plato;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PlatoControllerApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PlatoControllerApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PlatoControllerApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deletePlato
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Plato eliminado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deletePlatoCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plato/delete/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deletePlatoValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deletePlato(Async)");
        }

        return deletePlatoCall(id, _callback);

    }

    /**
     * Eliminar un plato por su ID
     * 
     * @param id  (required)
     * @return Boolean
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Plato eliminado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public Boolean deletePlato(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<Boolean> localVarResp = deletePlatoWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Eliminar un plato por su ID
     * 
     * @param id  (required)
     * @return ApiResponse&lt;Boolean&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Plato eliminado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Boolean> deletePlatoWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = deletePlatoValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Eliminar un plato por su ID (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Plato eliminado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deletePlatoAsync(@javax.annotation.Nonnull String id, final ApiCallback<Boolean> _callback) throws ApiException {

        okhttp3.Call localVarCall = deletePlatoValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for findAll2
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call findAll2Call(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plato/getAll";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call findAll2ValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return findAll2Call(_callback);

    }

    /**
     * Obtener todos los platos
     * 
     * @return List&lt;Plato&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public List<Plato> findAll2() throws ApiException {
        ApiResponse<List<Plato>> localVarResp = findAll2WithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Obtener todos los platos
     * 
     * @return ApiResponse&lt;List&lt;Plato&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Plato>> findAll2WithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = findAll2ValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<Plato>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtener todos los platos (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call findAll2Async(final ApiCallback<List<Plato>> _callback) throws ApiException {

        okhttp3.Call localVarCall = findAll2ValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<Plato>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getByNombre1
     * @param nombre  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByNombre1Call(@javax.annotation.Nonnull String nombre, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plato/getpornombre";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (nombre != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("nombre", nombre));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getByNombre1ValidateBeforeCall(@javax.annotation.Nonnull String nombre, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'nombre' is set
        if (nombre == null) {
            throw new ApiException("Missing the required parameter 'nombre' when calling getByNombre1(Async)");
        }

        return getByNombre1Call(nombre, _callback);

    }

    /**
     * Buscar platos por nombre
     * 
     * @param nombre  (required)
     * @return List&lt;Plato&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public List<Plato> getByNombre1(@javax.annotation.Nonnull String nombre) throws ApiException {
        ApiResponse<List<Plato>> localVarResp = getByNombre1WithHttpInfo(nombre);
        return localVarResp.getData();
    }

    /**
     * Buscar platos por nombre
     * 
     * @param nombre  (required)
     * @return ApiResponse&lt;List&lt;Plato&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Plato>> getByNombre1WithHttpInfo(@javax.annotation.Nonnull String nombre) throws ApiException {
        okhttp3.Call localVarCall = getByNombre1ValidateBeforeCall(nombre, null);
        Type localVarReturnType = new TypeToken<List<Plato>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Buscar platos por nombre (asynchronously)
     * 
     * @param nombre  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByNombre1Async(@javax.annotation.Nonnull String nombre, final ApiCallback<List<Plato>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getByNombre1ValidateBeforeCall(nombre, _callback);
        Type localVarReturnType = new TypeToken<List<Plato>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getByRestaurante
     * @param idRestaurante  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByRestauranteCall(@javax.annotation.Nonnull String idRestaurante, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plato/getporid";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (idRestaurante != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("idRestaurante", idRestaurante));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getByRestauranteValidateBeforeCall(@javax.annotation.Nonnull String idRestaurante, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idRestaurante' is set
        if (idRestaurante == null) {
            throw new ApiException("Missing the required parameter 'idRestaurante' when calling getByRestaurante(Async)");
        }

        return getByRestauranteCall(idRestaurante, _callback);

    }

    /**
     * Buscar platos por ID de restaurante
     * 
     * @param idRestaurante  (required)
     * @return List&lt;Plato&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public List<Plato> getByRestaurante(@javax.annotation.Nonnull String idRestaurante) throws ApiException {
        ApiResponse<List<Plato>> localVarResp = getByRestauranteWithHttpInfo(idRestaurante);
        return localVarResp.getData();
    }

    /**
     * Buscar platos por ID de restaurante
     * 
     * @param idRestaurante  (required)
     * @return ApiResponse&lt;List&lt;Plato&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Plato>> getByRestauranteWithHttpInfo(@javax.annotation.Nonnull String idRestaurante) throws ApiException {
        okhttp3.Call localVarCall = getByRestauranteValidateBeforeCall(idRestaurante, null);
        Type localVarReturnType = new TypeToken<List<Plato>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Buscar platos por ID de restaurante (asynchronously)
     * 
     * @param idRestaurante  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByRestauranteAsync(@javax.annotation.Nonnull String idRestaurante, final ApiCallback<List<Plato>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getByRestauranteValidateBeforeCall(idRestaurante, _callback);
        Type localVarReturnType = new TypeToken<List<Plato>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getByRestauranteAndNombre
     * @param idRestaurante  (required)
     * @param nombre  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByRestauranteAndNombreCall(@javax.annotation.Nonnull String idRestaurante, @javax.annotation.Nonnull String nombre, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plato/getporplatoynombre";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (idRestaurante != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("idRestaurante", idRestaurante));
        }

        if (nombre != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("nombre", nombre));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getByRestauranteAndNombreValidateBeforeCall(@javax.annotation.Nonnull String idRestaurante, @javax.annotation.Nonnull String nombre, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idRestaurante' is set
        if (idRestaurante == null) {
            throw new ApiException("Missing the required parameter 'idRestaurante' when calling getByRestauranteAndNombre(Async)");
        }

        // verify the required parameter 'nombre' is set
        if (nombre == null) {
            throw new ApiException("Missing the required parameter 'nombre' when calling getByRestauranteAndNombre(Async)");
        }

        return getByRestauranteAndNombreCall(idRestaurante, nombre, _callback);

    }

    /**
     * Buscar platos por restaurante y nombre
     * 
     * @param idRestaurante  (required)
     * @param nombre  (required)
     * @return List&lt;Plato&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public List<Plato> getByRestauranteAndNombre(@javax.annotation.Nonnull String idRestaurante, @javax.annotation.Nonnull String nombre) throws ApiException {
        ApiResponse<List<Plato>> localVarResp = getByRestauranteAndNombreWithHttpInfo(idRestaurante, nombre);
        return localVarResp.getData();
    }

    /**
     * Buscar platos por restaurante y nombre
     * 
     * @param idRestaurante  (required)
     * @param nombre  (required)
     * @return ApiResponse&lt;List&lt;Plato&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Plato>> getByRestauranteAndNombreWithHttpInfo(@javax.annotation.Nonnull String idRestaurante, @javax.annotation.Nonnull String nombre) throws ApiException {
        okhttp3.Call localVarCall = getByRestauranteAndNombreValidateBeforeCall(idRestaurante, nombre, null);
        Type localVarReturnType = new TypeToken<List<Plato>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Buscar platos por restaurante y nombre (asynchronously)
     * 
     * @param idRestaurante  (required)
     * @param nombre  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByRestauranteAndNombreAsync(@javax.annotation.Nonnull String idRestaurante, @javax.annotation.Nonnull String nombre, final ApiCallback<List<Plato>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getByRestauranteAndNombreValidateBeforeCall(idRestaurante, nombre, _callback);
        Type localVarReturnType = new TypeToken<List<Plato>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getByTag1
     * @param tag  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByTag1Call(@javax.annotation.Nonnull String tag, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plato/getportag";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (tag != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("tag", tag));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getByTag1ValidateBeforeCall(@javax.annotation.Nonnull String tag, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'tag' is set
        if (tag == null) {
            throw new ApiException("Missing the required parameter 'tag' when calling getByTag1(Async)");
        }

        return getByTag1Call(tag, _callback);

    }

    /**
     * Buscar platos por tag
     * 
     * @param tag  (required)
     * @return List&lt;Plato&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public List<Plato> getByTag1(@javax.annotation.Nonnull String tag) throws ApiException {
        ApiResponse<List<Plato>> localVarResp = getByTag1WithHttpInfo(tag);
        return localVarResp.getData();
    }

    /**
     * Buscar platos por tag
     * 
     * @param tag  (required)
     * @return ApiResponse&lt;List&lt;Plato&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Plato>> getByTag1WithHttpInfo(@javax.annotation.Nonnull String tag) throws ApiException {
        okhttp3.Call localVarCall = getByTag1ValidateBeforeCall(tag, null);
        Type localVarReturnType = new TypeToken<List<Plato>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Buscar platos por tag (asynchronously)
     * 
     * @param tag  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platos encontrados </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se han encontrado platos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByTag1Async(@javax.annotation.Nonnull String tag, final ApiCallback<List<Plato>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getByTag1ValidateBeforeCall(tag, _callback);
        Type localVarReturnType = new TypeToken<List<Plato>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPlatoById
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Plato encontrado </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se ha encontrado el plato </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parámetros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPlatoByIdCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plato/get/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPlatoByIdValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getPlatoById(Async)");
        }

        return getPlatoByIdCall(id, _callback);

    }

    /**
     * Obtener un plato por su ID
     * 
     * @param id  (required)
     * @return Plato
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Plato encontrado </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se ha encontrado el plato </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parámetros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public Plato getPlatoById(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<Plato> localVarResp = getPlatoByIdWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Obtener un plato por su ID
     * 
     * @param id  (required)
     * @return ApiResponse&lt;Plato&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Plato encontrado </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se ha encontrado el plato </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parámetros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Plato> getPlatoByIdWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = getPlatoByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Plato>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtener un plato por su ID (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Plato encontrado </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> No se ha encontrado el plato </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Parámetros incorrectos </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPlatoByIdAsync(@javax.annotation.Nonnull String id, final ApiCallback<Plato> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPlatoByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Plato>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPlatoIconUploadUrl
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> URL generada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Plato no encontrado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPlatoIconUploadUrlCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plato/icon-upload-url/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPlatoIconUploadUrlValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getPlatoIconUploadUrl(Async)");
        }

        return getPlatoIconUploadUrlCall(id, _callback);

    }

    /**
     * Obtener URL prefirmada para subir foto de plato
     * 
     * @param id  (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> URL generada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Plato no encontrado </td><td>  -  </td></tr>
     </table>
     */
    public String getPlatoIconUploadUrl(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<String> localVarResp = getPlatoIconUploadUrlWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Obtener URL prefirmada para subir foto de plato
     * 
     * @param id  (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> URL generada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Plato no encontrado </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> getPlatoIconUploadUrlWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = getPlatoIconUploadUrlValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtener URL prefirmada para subir foto de plato (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> URL generada </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Plato no encontrado </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPlatoIconUploadUrlAsync(@javax.annotation.Nonnull String id, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPlatoIconUploadUrlValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for register1
     * @param plato  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Plato registrado. false: Ya existía o hubo un error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call register1Call(@javax.annotation.Nonnull Plato plato, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = plato;

        // create path and map variables
        String localVarPath = "/plato/register";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call register1ValidateBeforeCall(@javax.annotation.Nonnull Plato plato, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'plato' is set
        if (plato == null) {
            throw new ApiException("Missing the required parameter 'plato' when calling register1(Async)");
        }

        return register1Call(plato, _callback);

    }

    /**
     * Registrar un nuevo plato
     * 
     * @param plato  (required)
     * @return Plato
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Plato registrado. false: Ya existía o hubo un error </td><td>  -  </td></tr>
     </table>
     */
    public Plato register1(@javax.annotation.Nonnull Plato plato) throws ApiException {
        ApiResponse<Plato> localVarResp = register1WithHttpInfo(plato);
        return localVarResp.getData();
    }

    /**
     * Registrar un nuevo plato
     * 
     * @param plato  (required)
     * @return ApiResponse&lt;Plato&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Plato registrado. false: Ya existía o hubo un error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Plato> register1WithHttpInfo(@javax.annotation.Nonnull Plato plato) throws ApiException {
        okhttp3.Call localVarCall = register1ValidateBeforeCall(plato, null);
        Type localVarReturnType = new TypeToken<Plato>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Registrar un nuevo plato (asynchronously)
     * 
     * @param plato  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Plato registrado. false: Ya existía o hubo un error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call register1Async(@javax.annotation.Nonnull Plato plato, final ApiCallback<Plato> _callback) throws ApiException {

        okhttp3.Call localVarCall = register1ValidateBeforeCall(plato, _callback);
        Type localVarReturnType = new TypeToken<Plato>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updatePlato
     * @param plato  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Plato actualizado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updatePlatoCall(@javax.annotation.Nonnull Plato plato, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = plato;

        // create path and map variables
        String localVarPath = "/plato/save";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updatePlatoValidateBeforeCall(@javax.annotation.Nonnull Plato plato, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'plato' is set
        if (plato == null) {
            throw new ApiException("Missing the required parameter 'plato' when calling updatePlato(Async)");
        }

        return updatePlatoCall(plato, _callback);

    }

    /**
     * Actualizar un plato existente
     * 
     * @param plato  (required)
     * @return Boolean
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Plato actualizado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public Boolean updatePlato(@javax.annotation.Nonnull Plato plato) throws ApiException {
        ApiResponse<Boolean> localVarResp = updatePlatoWithHttpInfo(plato);
        return localVarResp.getData();
    }

    /**
     * Actualizar un plato existente
     * 
     * @param plato  (required)
     * @return ApiResponse&lt;Boolean&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Plato actualizado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Boolean> updatePlatoWithHttpInfo(@javax.annotation.Nonnull Plato plato) throws ApiException {
        okhttp3.Call localVarCall = updatePlatoValidateBeforeCall(plato, null);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Actualizar un plato existente (asynchronously)
     * 
     * @param plato  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> true: Plato actualizado. false: No existía o hubo error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updatePlatoAsync(@javax.annotation.Nonnull Plato plato, final ApiCallback<Boolean> _callback) throws ApiException {

        okhttp3.Call localVarCall = updatePlatoValidateBeforeCall(plato, _callback);
        Type localVarReturnType = new TypeToken<Boolean>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
