/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.bomboplats.api;

import java.util.Objects;
import com.example.bomboplats.api.Direccion;
import com.example.bomboplats.api.Plato;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.example.bomboplats.api.JSON;

/**
 * Restaurante
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-07T19:05:09.591510200+02:00[Europe/Madrid]", comments = "Generator version: 7.21.0")
public class Restaurante {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_NOMBRE = "nombre";
  @SerializedName(SERIALIZED_NAME_NOMBRE)
  @javax.annotation.Nullable
  private String nombre;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_ICON_URLS = "iconUrls";
  @SerializedName(SERIALIZED_NAME_ICON_URLS)
  @javax.annotation.Nullable
  private List<String> iconUrls = new ArrayList<>();

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public static final String SERIALIZED_NAME_PLATOS = "platos";
  @SerializedName(SERIALIZED_NAME_PLATOS)
  @javax.annotation.Nullable
  private Set<Plato> platos = new LinkedHashSet<>();

  public static final String SERIALIZED_NAME_DIRECCIONES = "direcciones";
  @SerializedName(SERIALIZED_NAME_DIRECCIONES)
  @javax.annotation.Nullable
  private List<Direccion> direcciones = new ArrayList<>();

  public static final String SERIALIZED_NAME_RATING = "rating";
  @SerializedName(SERIALIZED_NAME_RATING)
  @javax.annotation.Nullable
  private Integer rating;

  public Restaurante() {
  }

  public Restaurante id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public Restaurante nombre(@javax.annotation.Nullable String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * Get nombre
   * @return nombre
   */
  @javax.annotation.Nullable
  public String getNombre() {
    return nombre;
  }

  public void setNombre(@javax.annotation.Nullable String nombre) {
    this.nombre = nombre;
  }


  public Restaurante description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public Restaurante iconUrls(@javax.annotation.Nullable List<String> iconUrls) {
    this.iconUrls = iconUrls;
    return this;
  }

  public Restaurante addIconUrlsItem(String iconUrlsItem) {
    if (this.iconUrls == null) {
      this.iconUrls = new ArrayList<>();
    }
    this.iconUrls.add(iconUrlsItem);
    return this;
  }

  /**
   * Get iconUrls
   * @return iconUrls
   */
  @javax.annotation.Nullable
  public List<String> getIconUrls() {
    return iconUrls;
  }

  public void setIconUrls(@javax.annotation.Nullable List<String> iconUrls) {
    this.iconUrls = iconUrls;
  }


  public Restaurante tags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
    return this;
  }

  public Restaurante addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public List<String> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }


  public Restaurante platos(@javax.annotation.Nullable Set<Plato> platos) {
    this.platos = platos;
    return this;
  }

  public Restaurante addPlatosItem(Plato platosItem) {
    if (this.platos == null) {
      this.platos = new LinkedHashSet<>();
    }
    this.platos.add(platosItem);
    return this;
  }

  /**
   * Get platos
   * @return platos
   */
  @javax.annotation.Nullable
  public Set<Plato> getPlatos() {
    return platos;
  }

  public void setPlatos(@javax.annotation.Nullable Set<Plato> platos) {
    this.platos = platos;
  }


  public Restaurante direcciones(@javax.annotation.Nullable List<Direccion> direcciones) {
    this.direcciones = direcciones;
    return this;
  }

  public Restaurante addDireccionesItem(Direccion direccionesItem) {
    if (this.direcciones == null) {
      this.direcciones = new ArrayList<>();
    }
    this.direcciones.add(direccionesItem);
    return this;
  }

  /**
   * Get direcciones
   * @return direcciones
   */
  @javax.annotation.Nullable
  public List<Direccion> getDirecciones() {
    return direcciones;
  }

  public void setDirecciones(@javax.annotation.Nullable List<Direccion> direcciones) {
    this.direcciones = direcciones;
  }


  public Restaurante rating(@javax.annotation.Nullable Integer rating) {
    this.rating = rating;
    return this;
  }

  /**
   * Get rating
   * @return rating
   */
  @javax.annotation.Nullable
  public Integer getRating() {
    return rating;
  }

  public void setRating(@javax.annotation.Nullable Integer rating) {
    this.rating = rating;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Restaurante restaurante = (Restaurante) o;
    return Objects.equals(this.id, restaurante.id) &&
        Objects.equals(this.nombre, restaurante.nombre) &&
        Objects.equals(this.description, restaurante.description) &&
        Objects.equals(this.iconUrls, restaurante.iconUrls) &&
        Objects.equals(this.tags, restaurante.tags) &&
        Objects.equals(this.platos, restaurante.platos) &&
        Objects.equals(this.direcciones, restaurante.direcciones) &&
        Objects.equals(this.rating, restaurante.rating);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nombre, description, iconUrls, tags, platos, direcciones, rating);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Restaurante {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    iconUrls: ").append(toIndentedString(iconUrls)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    platos: ").append(toIndentedString(platos)).append("\n");
    sb.append("    direcciones: ").append(toIndentedString(direcciones)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "nombre", "description", "iconUrls", "tags", "platos", "direcciones", "rating"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Restaurante
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Restaurante.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Restaurante is not found in the empty JSON string", Restaurante.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Restaurante.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Restaurante` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("nombre") != null && !jsonObj.get("nombre").isJsonNull()) && !jsonObj.get("nombre").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `nombre` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nombre").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("iconUrls") != null && !jsonObj.get("iconUrls").isJsonNull() && !jsonObj.get("iconUrls").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `iconUrls` to be an array in the JSON string but got `%s`", jsonObj.get("iconUrls").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
      if (jsonObj.get("platos") != null && !jsonObj.get("platos").isJsonNull()) {
        JsonArray jsonArrayplatos = jsonObj.getAsJsonArray("platos");
        if (jsonArrayplatos != null) {
          // ensure the json data is an array
          if (!jsonObj.get("platos").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `platos` to be an array in the JSON string but got `%s`", jsonObj.get("platos").toString()));
          }

          // validate the optional field `platos` (array)
          for (int i = 0; i < jsonArrayplatos.size(); i++) {
            Plato.validateJsonElement(jsonArrayplatos.get(i));
          };
        }
      }
      if (jsonObj.get("direcciones") != null && !jsonObj.get("direcciones").isJsonNull()) {
        JsonArray jsonArraydirecciones = jsonObj.getAsJsonArray("direcciones");
        if (jsonArraydirecciones != null) {
          // ensure the json data is an array
          if (!jsonObj.get("direcciones").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `direcciones` to be an array in the JSON string but got `%s`", jsonObj.get("direcciones").toString()));
          }

          // validate the optional field `direcciones` (array)
          for (int i = 0; i < jsonArraydirecciones.size(); i++) {
            Direccion.validateJsonElement(jsonArraydirecciones.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Restaurante.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Restaurante' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Restaurante> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Restaurante.class));

       return (TypeAdapter<T>) new TypeAdapter<Restaurante>() {
           @Override
           public void write(JsonWriter out, Restaurante value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Restaurante read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Restaurante given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Restaurante
   * @throws IOException if the JSON string is invalid with respect to Restaurante
   */
  public static Restaurante fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Restaurante.class);
  }

  /**
   * Convert an instance of Restaurante to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

