/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.bomboplats.api;

import com.example.bomboplats.api.invoker.ApiException;
import com.example.bomboplats.model.Pedido;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PedidoControllerApi
 */
@Disabled
public class PedidoControllerApiTest {

    private final PedidoControllerApi api = new PedidoControllerApi();

    /**
     * Borrar un pedido
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePedidoTest() throws ApiException {
        String id = null;
        Boolean response = api.deletePedido(id);
        // TODO: test validations
    }

    /**
     * Obtener todos los pedidos
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findAll3Test() throws ApiException {
        List<Pedido> response = api.findAll3();
        // TODO: test validations
    }

    /**
     * Obtener pedidos segun su estado
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPedidoByEstadoTest() throws ApiException {
        String estado = null;
        List<Pedido> response = api.getPedidoByEstado(estado);
        // TODO: test validations
    }

    /**
     * Obtener un pedido segun su ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPedidoByIdTest() throws ApiException {
        String id = null;
        Pedido response = api.getPedidoById(id);
        // TODO: test validations
    }

    /**
     * Obtener todos los pedidos que se han hecho de un plato según su id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPedidoByPlatoTest() throws ApiException {
        String plato = null;
        List<Pedido> response = api.getPedidoByPlato(plato);
        // TODO: test validations
    }

    /**
     * Obtener todos los pedidos de un usuario según su id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPedidoByUserTest() throws ApiException {
        String user = null;
        List<Pedido> response = api.getPedidoByUser(user);
        // TODO: test validations
    }

    /**
     * Obtener unicamente el id de los pedidos
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPedidosIDsTest() throws ApiException {
        List<String> response = api.getPedidosIDs();
        // TODO: test validations
    }

    /**
     * Registrar un pedido
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void register2Test() throws ApiException {
        Pedido pedido = null;
        Pedido response = api.register2(pedido);
        // TODO: test validations
    }

    /**
     * Actualizar un pedido
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePedidoTest() throws ApiException {
        Pedido pedido = null;
        Boolean response = api.updatePedido(pedido);
        // TODO: test validations
    }

}
