/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.bomboplats.api;

import com.example.bomboplats.api.invoker.ApiException;
import com.example.bomboplats.model.LoginAttempt;
import com.example.bomboplats.model.Plato;
import com.example.bomboplats.model.User;
import com.example.bomboplats.model.UserRegister;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserControllerApi
 */
@Disabled
public class UserControllerApiTest {

    private final UserControllerApi api = new UserControllerApi();

    /**
     * Generar link para subir fotos de usuarios al S3
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createImageUrlTest() throws ApiException {
        String id = null;
        String response = api.createImageUrl(id);
        // TODO: test validations
    }

    /**
     * Eliminar un usuario
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteByIDTest() throws ApiException {
        String id = null;
        Boolean response = api.deleteByID(id);
        // TODO: test validations
    }

    /**
     * Obtener todos los usuarios
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findAllTest() throws ApiException {
        List<User> response = api.findAll();
        // TODO: test validations
    }

    /**
     * Obtener un usuario por su Email
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByEmailTest() throws ApiException {
        String email = null;
        User response = api.getByEmail(email);
        // TODO: test validations
    }

    /**
     * Obtener un usuario por su ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIDTest() throws ApiException {
        String id = null;
        User response = api.getByID(id);
        // TODO: test validations
    }

    /**
     * Obtener los platos favoritos de un usuario
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPlatosFavoritosTest() throws ApiException {
        String id = null;
        List<Plato> response = api.getPlatosFavoritos(id);
        // TODO: test validations
    }

    /**
     * Obtener todos los IDs
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserIDsTest() throws ApiException {
        List<String> response = api.getUserIDs();
        // TODO: test validations
    }

    /**
     * Comprueba el login de un usuario
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void loginTest() throws ApiException {
        LoginAttempt loginAttempt = null;
        Boolean response = api.login(loginAttempt);
        // TODO: test validations
    }

    /**
     * Registrar un usuario
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registerUserTest() throws ApiException {
        UserRegister userRegister = null;
        User response = api.registerUser(userRegister);
        // TODO: test validations
    }

    /**
     * Actualizar la contraseña de un usuario segun su id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePasswordTest() throws ApiException {
        String userId = null;
        String password = null;
        Boolean response = api.updatePassword(userId, password);
        // TODO: test validations
    }

    /**
     * Actualizar información de un usuario
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateUserTest() throws ApiException {
        User user = null;
        Boolean response = api.updateUser(user);
        // TODO: test validations
    }

}
